# Generated by Django 4.0.3 on 2022-03-20 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Members', '0023_auto_20210701_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='ritfacultybio',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nontechnical',
            name='team',
            field=models.CharField(choices=[('WEB', 'Website and Design'), ('SPR', 'Public Relations and Sponsorship'), ('SM', 'Social Media'), ('DOC', 'Documentation'), ('VE', 'Video Editing')], max_length=4),
        ),
    ]
