# Generated by Django 4.0.3 on 2022-03-20 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Members', '0024_faculty_ritfacultybio_alter_nontechnical_team'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faculty',
            old_name='ritfacultybio',
            new_name='facultybio',
        ),
        migrations.AlterField(
            model_name='nontechnical',
            name='team',
            field=models.CharField(choices=[('Des', 'Design'), ('SPR', 'Public Relations and Sponsorship'), ('SM', 'Social Media'), ('DOC', 'Documentation'), ('VE', 'Video Editing'), ('Web', 'Web Development')], max_length=4),
        ),
        migrations.AlterField(
            model_name='rocketry',
            name='subsystem',
            field=models.CharField(choices=[('AS', 'Aerodynamics and Structures'), ('GCS', 'Guidance and Control System'), ('PS', 'Propulsion System'), ('AV', 'Avionics'), ('RNR', 'Research and Recovery')], max_length=5),
        ),
    ]
